name: Build RPM

on:
  push:
    tags: ['v*']
    branches: [main]
  workflow_dispatch:

jobs:
  rpm:
    uses: xibo-players/.github/.github/workflows/build-rpm.yml@main
    with:
      package-name: xibo-kiosk
      rpm-spec: 'rpm/xibo-kiosk.spec'
      source-tarball: 'full'
      default-version: '1.0.0'
      gpg-sign: true
    secrets: inherit
